use_frameworks!

target 'XHUserStatistics_Example' do
  pod 'XHUserStatistics', :path => '../'

  target 'XHUserStatistics_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
